name: Update Requires Headers

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-headers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch the latest WooCommerce release
      - name: Fetch Latest WooCommerce Release
        id: fetch_wc_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/woocommerce/woocommerce/releases/latest | jq -r '.tag_name')
          echo "Latest WooCommerce Release: $LATEST_RELEASE"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          curl -L -o woocommerce.zip "https://github.com/woocommerce/woocommerce/releases/download/$LATEST_RELEASE/woocommerce.zip"

      # Step 3: Unzip the WooCommerce release
      - name: Unzip WooCommerce Release
        run: |
          unzip -q woocommerce.zip

      # Step 4: Configure Git Author Identity
      - name: Configure Git Author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 5: Ignore Unwanted Files
      - name: Ignore Unwanted Files
        run: |
          echo "woocommerce/" >> .gitignore
          echo "woocommerce.zip" >> .gitignore
          git add .gitignore
          git commit -m "Add .gitignore to exclude unnecessary files" || echo "No changes to commit"

      # Step 7: Checkout Base Branch
      - name: Checkout Base Branch
        run: |
          git fetch origin
          git checkout main # Replace 'main' with your default branch name
          git pull origin main

      # Step 8: Create a New Branch
      - name: Create New Branch
        run: |
          BRANCH_NAME="update-requires-headers-$(date +%Y%m%d%H%M%S)-$RANDOM"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      # Step 9: Compare and Update Headers
      - name: Compare and Update Headers
        id: compare_and_update
        run: |
          WC_CORE_FILE="woocommerce/woocommerce.php"
          EXTENSION_FILE="woocommerce-zatca-invoices.php"
          CHANGES_MADE=false

          REQUIRES_AT_LEAST=$(grep -oP 'Requires at least: \K[\d.]+' "$WC_CORE_FILE")
          REQUIRES_PHP=$(grep -oP 'Requires PHP: \K[\d.]+' "$WC_CORE_FILE")

          CURRENT_REQUIRES_AT_LEAST=$(grep -oP 'Requires at least: \K[\d.]+' "$EXTENSION_FILE" || echo "")
          CURRENT_REQUIRES_PHP=$(grep -oP 'Requires PHP: \K[\d.]+' "$EXTENSION_FILE" || echo "")
          WC_REQUIRES_AT_LEAST=$(grep -oP 'WC requires at least: \K[\d.]+' "$EXTENSION_FILE" || echo "")

          if [ "$CURRENT_REQUIRES_AT_LEAST" != "$REQUIRES_AT_LEAST" ] || [ "$CURRENT_REQUIRES_PHP" != "$REQUIRES_PHP" ] || [ "$WC_REQUIRES_AT_LEAST" != "$LATEST_RELEASE" ]; then
            echo "Headers are outdated. Updating..."
            sed -i "s/Requires at least: .*/Requires at least: $REQUIRES_AT_LEAST/" "$EXTENSION_FILE"
            sed -i "s/Requires PHP: .*/Requires PHP: $REQUIRES_PHP/" "$EXTENSION_FILE"
            sed -i "s/WC requires at least: .*/WC requires at least: $LATEST_RELEASE/" "$EXTENSION_FILE"
            git add "$EXTENSION_FILE"
            git commit -m "Update Requires headers to match WooCommerce $LATEST_RELEASE" || echo "No changes to commit"
            CHANGES_MADE=true
          else
            echo "Headers are already up to date. No changes needed."
          fi

          echo "CHANGES_MADE=$CHANGES_MADE" >> $GITHUB_ENV
      # Step 6: Clean Untracked Files
      - name: Clean Untracked Files
        run: |
          git clean -fdx

      # Step 10: Create Pull Request (Only if Changes Are Made)
      - name: Create Pull Request
        if: env.CHANGES_MADE == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main # Set the base branch to 'main' or your default branch
          commit-message: "Update Requires headers"
          title: "Update Requires headers for WooCommerce compatibility"
          body: |
            This PR updates the following headers to ensure compatibility with the latest WooCommerce release:
            - `Requires at least`: $REQUIRES_AT_LEAST
            - `Requires PHP`: $REQUIRES_PHP
            - `WC requires at least`: $LATEST_RELEASE

            Please review and merge.
