name: Update Requires Headers

on:
  schedule:
    - cron: '0 0 * * 5' # Run every Friday at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-headers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch the latest WooCommerce release
      - name: Fetch Latest WooCommerce Release
        id: fetch_wc_release
        run: |
          # Download the latest WooCommerce release
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/woocommerce/woocommerce/releases/latest | jq -r '.tag_name')
          curl -L -o woocommerce.zip "https://github.com/woocommerce/woocommerce/releases/download/$LATEST_RELEASE/woocommerce.zip"

          # Unzip WooCommerce release
          unzip -q woocommerce.zip

          # Extract minor version for WC requires at least
          MAJOR_VERSION=$(echo "$LATEST_RELEASE" | grep -oE '^[0-9]+')
          MINOR_VERSION=$(echo "$LATEST_RELEASE" | grep -oE '^[0-9]+\.[0-9]+' | cut -d. -f2)
          ADJUSTED_MINOR_VERSION=$((MINOR_VERSION - 2))

          if [ "$ADJUSTED_MINOR_VERSION" -lt 0 ]; then
            ADJUSTED_MINOR_VERSION=0
          fi

          LATEST_MINOR_RELEASE="$MAJOR_VERSION.$ADJUSTED_MINOR_VERSION"

          echo "Latest WooCommerce Release: $LATEST_RELEASE"
          echo "Adjusted Minor Release: $LATEST_MINOR_RELEASE"

          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          echo "LATEST_MINOR_RELEASE=$LATEST_MINOR_RELEASE" >> $GITHUB_ENV

      # Step 3: Create and Checkout a New Branch
      - name: Create and Checkout Branch
        run: |
          BRANCH_NAME="tweak/update-requires-headers-${{ env.LATEST_RELEASE }}"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      # Step 4: Compare and Update Headers
      - name: Compare and Update Headers
        id: compare_and_update
        run: |
          WC_CORE_FILE="woocommerce/woocommerce.php"
          EXTENSION_FILE="woocommerce-zatca-invoices.php"
          CHANGES_MADE=false

          REQUIRES_AT_LEAST=$(grep -oP 'Requires at least: \K[\d.]+' "$WC_CORE_FILE")
          REQUIRES_PHP=$(grep -oP 'Requires PHP: \K[\d.]+' "$WC_CORE_FILE")
          LATEST_MINOR_RELEASE=$(echo "$LATEST_RELEASE" | grep -oE '^[0-9]+\.[0-9]+' | awk -F. '{printf("%d.%d", $1, $2-2 < 0 ? 0 : $2-2)}')
          echo "REQUIRES_AT_LEAST=$REQUIRES_AT_LEAST" >> $GITHUB_ENV
          echo "REQUIRES_PHP=$REQUIRES_PHP" >> $GITHUB_ENV

                    # Check and update or add the 'Requires at least' header
          if grep -qE "^\s*\* Requires at least:" "$EXTENSION_FILE"; then
            echo "Updating 'Requires at least' header."
            sed -i "s#^\s*\* Requires at least:.*# \* Requires at least: $REQUIRES_AT_LEAST#" "$EXTENSION_FILE"
          else
            echo "Adding missing 'Requires at least' header."
            sed -i "/^\s*\* Version:/a \\ \\* Requires at least: $REQUIRES_AT_LEAST" "$EXTENSION_FILE"
          fi
          CHANGES_MADE=true

          # Check and update or add the 'Requires PHP' header
          if grep -qE "^\s*\* Requires PHP:" "$EXTENSION_FILE"; then
            echo "Updating 'Requires PHP' header."
            sed -i "s#^\s*\* Requires PHP:.*# \* Requires PHP: $REQUIRES_PHP#" "$EXTENSION_FILE"
          else
            echo "Adding missing 'Requires PHP' header."
            sed -i "/^\s*\* Version:/a \\ \\* Requires PHP: $REQUIRES_PHP" "$EXTENSION_FILE"
          fi
          CHANGES_MADE=true

          # Check and update or add the 'WC requires at least' header
          if grep -qE "^\s*\* WC requires at least:" "$EXTENSION_FILE"; then
            echo "Updating 'WC requires at least' header."
            sed -i "s#^\s*\* WC requires at least:.*# \* WC requires at least: $LATEST_MINOR_RELEASE#" "$EXTENSION_FILE"
          else
            echo "Adding missing 'WC requires at least' header."
            sed -i "/^\s*\* Version:/a \\ \\* WC requires at least: $LATEST_MINOR_RELEASE" "$EXTENSION_FILE"
          fi
          CHANGES_MADE=true

          echo "CHANGES_MADE=$CHANGES_MADE" >> $GITHUB_ENV

      # Step 5: Ignore Unwanted Files
      - name: Ignore Unwanted Files
        run: |
          echo "woocommerce/" >> .gitignore
          echo "woocommerce.zip" >> .gitignore
          git clean -fdx

      # Step 5: Push Branch
      - name: Push Branch
        if: env.CHANGES_MADE == 'true'
        run: |
          git push --set-upstream origin ${{ env.BRANCH_NAME }}

      # Step 6: Create Pull Request
      - name: Create Pull Request
        if: env.CHANGES_MADE == 'true'
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          add-paths: |
            woocommerce-zatca-invoices.php
          commit-message: "Update Requires headers"
          title: "Update Requires headers for WooCommerce compatibility"
          reviewers: abdalsalaam
          body: |
            This PR updates the following headers to ensure compatibility with the latest WooCommerce release:
            - `Requires at least`: ${{ env.REQUIRES_AT_LEAST }}
            - `Requires PHP`: ${{ env.REQUIRES_PHP }}
            - `WC requires at least`: ${{ env.LATEST_MINOR_RELEASE }}

            Please review and merge.